# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f13036de8018f8be4a006ebc3f81f55948117050fb7d17afd0b9eda41c128c6cbcccdad603cc64efb3a745c9a9943bf3dacf0a1b4c89fea266fe244acd8a4ab

test:
  secret_key_base: 1bbbf7d2156787b106db06b67ec3caa3b78a4e5ace585b1a77e048c7604e15673d9539f20e58e0d43301048036a0a46c12125355c61c4db153d12f9c91f03677

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
